  version: "3"
  services:
    django:
      build: .
      container_name: django_appo
      ports:
        - "8000:8000"
      volumes:
        - .:/app
        - static_volume:/usr/src/app/static
        - media_volumes:/usr/src/app/media
      restart: always
      command: sh -c "python3 manage.py makemigrations && python3 manage.py migrate && gunicorn config.wsgi:application --bind 0.0.0.0:8000"


    nginx:
      image: nginx
      ports:
        - 81:81
      volumes:
        - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        - static_volume:/usr/src/app/static
        - media_volumes:/usr/src/app/media
      depends_on:
        - django

  volumes:
    static_volume:
    media_volumes:
